# Generated by Django 4.2.29 on 2026-04-07 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 - Rất không hài lòng'), (2, '2 - Không hài lòng'), (3, '3 - Bình thường'), (4, '4 - Hài lòng'), (5, '5 - Rất hài lòng')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_type', models.CharField(blank=True, help_text='Type of feedback: accuracy, relevance, speed, etc.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, help_text='Tóm tắt cuộc hội thoại')),
                ('topics', models.JSONField(blank=True, default=list, help_text='Các chủ đề đã thảo luận')),
                ('entities', models.JSONField(blank=True, default=dict, help_text='Các entity được đề cập')),
                ('intent_history', models.JSONField(blank=True, default=list, help_text='Lịch sử intent')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='app.chatsession')),
            ],
            options={
                'db_table': 'conversation_contexts',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['customer_id', '-updated_at'], name='chat_sessio_custome_609570_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-created_at'], name='chat_sessio_created_a0e39a_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chatsession'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.chatmessage'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chat_messag_session_4a3fea_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='chat_messag_role_ddd811_idx'),
        ),
    ]
