#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE product_db OWNER $POSTGRES_USER;
    CREATE DATABASE order_db OWNER $POSTGRES_USER;
    CREATE DATABASE pay_db OWNER $POSTGRES_USER;
    CREATE DATABASE ship_db OWNER $POSTGRES_USER;
    CREATE DATABASE comment_db OWNER $POSTGRES_USER;
    CREATE DATABASE cart_db OWNER $POSTGRES_USER;
EOSQL