# Generated by Django 6.0.3 on 2026-03-31 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True, unique=True)),
                ('segment', models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular'), ('New', 'New'), ('Churned', 'Churned')], default='Regular', max_length=20)),
                ('segment_confidence', models.FloatField(default=0.0)),
                ('segment_probabilities', models.JSONField(blank=True, default=dict)),
                ('churn_risk', models.FloatField(default=0.0)),
                ('churn_level', models.CharField(default='Low', max_length=20)),
                ('predicted_categories', models.JSONField(blank=True, default=list)),
                ('engagement_score', models.FloatField(default=50.0)),
                ('rfm_recency', models.IntegerField(default=0)),
                ('rfm_frequency', models.IntegerField(default=0)),
                ('rfm_monetary', models.FloatField(default=0.0)),
                ('rfm_score', models.IntegerField(default=0)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Behavior',
                'verbose_name_plural': 'Customer Behaviors',
                'db_table': 'customer_behaviors',
                'ordering': ['-last_analyzed'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model_path', models.CharField(max_length=500)),
                ('processor_path', models.CharField(blank=True, max_length=500, null=True)),
                ('config_path', models.CharField(blank=True, max_length=500, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('training_duration_seconds', models.IntegerField(default=0)),
                ('accuracy_segment', models.FloatField(default=0.0)),
                ('accuracy_category', models.FloatField(default=0.0)),
                ('auc_churn', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model Metadata',
                'verbose_name_plural': 'Model Metadata',
                'db_table': 'model_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True)),
                ('analysis_type', models.CharField(choices=[('full_analysis', 'Full Analysis'), ('segment', 'Segment Classification'), ('churn', 'Churn Prediction'), ('category', 'Category Prediction'), ('rfm', 'RFM Analysis'), ('insights', 'Customer Insights')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'analysis_type'], name='analysis_re_custome_a108c6_idx'), models.Index(fields=['customer_id', 'created_at'], name='analysis_re_custome_64b12c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('purchase', 'Purchase'), ('search', 'Search'), ('review', 'Review'), ('wishlist_add', 'Add to Wishlist'), ('wishlist_remove', 'Remove from Wishlist'), ('login', 'Login'), ('logout', 'Logout'), ('signup', 'Sign Up')], max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Behavior Event',
                'verbose_name_plural': 'Behavior Events',
                'db_table': 'behavior_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer_id', 'timestamp'], name='behavior_ev_custome_f7b15f_idx'), models.Index(fields=['event_type', 'timestamp'], name='behavior_ev_event_t_931e11_idx'), models.Index(fields=['customer_id', 'event_type'], name='behavior_ev_custome_05af23_idx')],
            },
        ),
    ]
