from django.urls import path
from .views import (
    HealthCheck,
    CategoryListCreate,
    CategoryDetail,
    BookCatalogListCreate,
    ProductCatalogListCreate,
    ProductCatalogDetail,
    ProductStockAdjust,
    LegacyBooksListCreate,
    LegacyBookDetail,
    LegacyClothesListCreate,
    LegacyClotheDetail,
    LegacyStockAdjust,
    SeedCatalogData,
    SimilarProducts,
    SyncExternalProducts,
)

urlpatterns = [
    path('health/', HealthCheck.as_view()),
    path('categories/', CategoryListCreate.as_view()),
    path('categories/<int:pk>/', CategoryDetail.as_view()),
    path('book-catalogs/', BookCatalogListCreate.as_view()),
    path('products/', ProductCatalogListCreate.as_view()),
    path('products/<int:pk>/', ProductCatalogDetail.as_view()),
    path('products/<int:pk>/similar/', SimilarProducts.as_view()),
    path('products/<int:pk>/reduce-stock/', ProductStockAdjust.as_view(), {'action': 'reduce'}),
    path('products/<int:pk>/restore-stock/', ProductStockAdjust.as_view(), {'action': 'restore'}),
    path('books/', LegacyBooksListCreate.as_view()),
    path('books/<int:pk>/', LegacyBookDetail.as_view()),
    path('books/<int:pk>/reduce-stock/', LegacyStockAdjust.as_view(), {'action': 'reduce'}),
    path('books/<int:pk>/restore-stock/', LegacyStockAdjust.as_view(), {'action': 'restore'}),
    path('clothes/', LegacyClothesListCreate.as_view()),
    path('clothes/<int:pk>/', LegacyClotheDetail.as_view()),
    path('clothes/<int:pk>/reduce-stock/', LegacyStockAdjust.as_view(), {'action': 'reduce'}),
    path('clothes/<int:pk>/restore-stock/', LegacyStockAdjust.as_view(), {'action': 'restore'}),
    path('seed/sample-data/', SeedCatalogData.as_view()),
    path('integrations/sync/', SyncExternalProducts.as_view()),
]
