import os
import pandas as pd
from neo4j import GraphDatabase
from pathlib import Path

class Neo4jSync:
    def __init__(self):
        self.uri = os.getenv("NEO4J_URI", "bolt://neo4j-db:7687")
        self.user = os.getenv("NEO4J_USER", "neo4j")
        self.password = os.getenv("NEO4J_PASSWORD", "password")
        self.driver = GraphDatabase.driver(self.uri, auth=(self.user, self.password))

    def close(self):
        self.driver.close()

    def create_constraints(self):
        with self.driver.session() as session:
            session.run("CREATE CONSTRAINT user_id_unique IF NOT EXISTS FOR (u:User) REQUIRE u.id IS UNIQUE")
            session.run("CREATE CONSTRAINT product_id_unique IF NOT EXISTS FOR (p:Product) REQUIRE p.id IS UNIQUE")

    def sync_from_csv(self, csv_path):
        df = pd.read_csv(csv_path)
        rows = df.to_dict(orient="records")
        
        with self.driver.session() as session:
            session.execute_write(self._insert_batch, rows)
        print(f"Synced {len(rows)} rows to Neo4j.")

    @staticmethod
    def _insert_batch(tx, rows):
        tx.run(
            """
            UNWIND $rows AS row
            MERGE (u:User {id: row.user_id})
            MERGE (p:Product {id: row.product_id})
            CREATE (u)-[:INTERACTED {action: row.action, timestamp: row.timestamp}]->(p)
            """,
            rows=rows,
        )

if __name__ == "__main__":
    # Example usage
    syncer = Neo4jSync()
    syncer.create_constraints()
    # Path to the data generated by the assignment script
    data_path = "D:/AI_ecommerce/assignment_ai_service/data_user500.csv"
    if os.path.exists(data_path):
        syncer.sync_from_csv(data_path)
    syncer.close()
